---
trigger:
  - main
pool:
  vmImage: Windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $password = ConvertTo-SecureString "$(vmPassword)" -AsPlainText -Force
      $cred = New-Object System.Management.Automation.PSCredential("admin" , $password)
