name: Install Packages on Windows VM

on:
  push:
    branches:
      - main

jobs:
  install_packages:
    runs-on: windows-latest
    steps:
      - name: Setup WinRM Client and Install Packages
        env:
          VM_IP: ${{ secrets.VM_IP }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          # Step 1: Start WinRM service
          net start winrm

          # Step 2: Configure WinRM quick config
          winrm quickconfig -quiet

          # Step 3: Allow unencrypted traffic
          Set-Item -Path WSMan:\localhost\Client\AllowUnencrypted -Value $true

          # Step 4: Enable Basic Authentication
          Set-Item -Path WSMan:\localhost\Client\Auth\Basic -Value $true

          # Step 5: Add VM IP to TrustedHosts (handle empty TrustedHosts)
          $trustedHosts = Get-Item -Path WSMan:\localhost\Client\TrustedHosts -ErrorAction SilentlyContinue
          if ($trustedHosts.Value -notlike "*$env:VM_IP*") {
              Set-Item -Path WSMan:\localhost\Client\TrustedHosts -Value "$env:VM_IP" -Concatenate
          }

          # Step 6: Create secure credential
          $password = ConvertTo-SecureString "$env:VM_PASSWORD" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ("$env:VM_USER", $password)

          # Step 7: Establish WinRM session
          $session = New-PSSession -ComputerName "$env:VM_IP" -Port 5985 -Credential $credential -Authentication Basic

          # Step 8: Run installation commands
          Invoke-Command -Session $session -ScriptBlock {
            Write-Host "Installing Nginx..."
            choco install nginx -y

            Write-Host "Installing Python 3..."
            choco install python -y

            Write-Host "Installing Visual Studio Build Tools (C++)..."
            choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64" -y

            # Optional: Verify installations
            nginx -v
            python --version
            cl.exe /?
          }

          # Step 9: Close session
          Remove-PSSession -Session $session
